apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: rdspostgresql
spec:
  providerConfigRef:
    name: aws-credentials
  forProvider:
    region: ap-south-1
    dbInstanceClass: db.t2.small
    masterUsername: master
    allocatedStorage: 10
    engine: postgres
    engineVersion: "12"
    skipFinalSnapshotBeforeDeletion: true
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: rds-conn