# XRD for an API to create a bucket with and a IAM user for bucket access
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbucketwithcredentials.reference.imarunrk.com
spec:
  group: reference.imarunrk.com
  names:
    kind: XBucketWithCredential
    plural: xbucketwithcredentials
  claimNames:
    kind: BucketWithCredential
    plural: bucketwithcredentials
  connectionSecretKeys:
    - bucket_url
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          # S3 bucket name is the API input
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  bucketName:
                    description: The name of the S3 bucket 
                    type: string
                required:
                  - bucketName
            required:
              - parameters
          # policyARN is the API output, used to feed the inner IAM XR
          status:
            type: object
            properties:
              policyARN:
                description: Policy ARN to patch back to the IAM XR
                type: string