apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.version-test.imarunrk.com
spec:
  group: version-test.imarunrk.com
  names:
    kind: XBuckets
    plural: xbuckets
  versions:
  - name: v1.0
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    type: string
                required:
                - region
            required:
            - parameters