apiVersion: "apiextensions.k8s.io/v1beta1"
kind: "CustomResourceDefinition"
metadata:
  name: "clouddbs.book.imarunrk.com"
spec:
  group: "book.imarunrk.com"
  version: "v1"
  scope: "Namespaced"
  names:
    plural: "clouddbs"
    singular: "clouddb"
    kind: "CloudDB"
  validation:
    openAPIV3Schema:
      required: ["spec"]
      properties:
        spec:
         required: ["type","cloud"]
         properties:
           type:
              type: "string"
              minimum: 1
           cloud:
              type: "string"
              minimum: 1
