apiVersion: container.gcp.crossplane.io/v1beta2
kind: Cluster
metadata:
  name: gke-for-helm-deployment
spec:
  providerConfigRef:
    name: gcp-credentials-project-1
  forProvider:
    location: us-west2
    loggingService: logging.googleapis.com/kubernetes
    monitoringService: monitoring.googleapis.com/kubernetes
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: secret-gke-for-helm-deployment
---
apiVersion: container.gcp.crossplane.io/v1beta1
kind: NodePool
metadata:
  name: gke-node-for-helm-deployment
spec:
  providerConfigRef:
    name: gcp-credentials-project-1
  forProvider:
    autoscaling:
      autoprovisioned: false
      enabled: true
      maxNodeCount: 4
      minNodeCount: 4 
    clusterRef:
      name: gke-for-helm-deployment
    config:
      machineType: e2-medium
    initialNodeCount: 4
    locations:
      - "us-west2-a"