apiVersion: alpha-beta.imarunrk.com/v1
kind: GCPdb
metadata:
  # Claims in alpha namespace
  namespace: alpha
  name: postgres-db
spec:
  # refer to the postgres composition
  compositionRef:
    name: postgres
  # save connection details as secret - db-conn
  writeConnectionSecretToRef:
    name: db-conn
  parameters:
    size: SMALL