apiVersion: alpha-beta.imarunrk.com/v1
kind: GCPdb
metadata:
  # Claims in alpha namespace
  namespace: alpha
  name: mysql-db
spec:
  # refer to the mysql composition
  compositionRef:
    name: mysql
  # save connection details as secret - db-conn
  writeConnectionSecretToRef:
    name: db-conn2
  parameters:
    size: SMALL
