apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gcp-application
spec:
  compositeTypeRef:
    apiVersion: nested-xr.imarunrk.com/v1
    kind: XApplication
  resources:
  - name: cluster
    base:
      apiVersion: nested-xr.imarunrk.com/v1
      kind: XGCPCluster
      spec:
        parameters:
          region: us-central1-b
          autopilot: true
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.parameters.region
  - name: cloudsqlinstance
    base:
      apiVersion: database.gcp.crossplane.io/v1beta1
      kind: CloudSQLInstance
      spec:
        providerConfigRef:
          name: gcp-credentials-project-1
        forProvider:
          databaseVersion: MYSQL_5_7
          region: us-central1
          settings:
            tier: db-g1-small
    patches:
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.region
      toFieldPath: spec.forProvider.region
