# XRD for an XR API to create a IAM user with a specific resource access  
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xiamwithcredentials.reference.imarunrk.com
spec:
  group: reference.imarunrk.com
  names:
    kind: XIAMWithCredential
    plural: xiamwithcredentials
  connectionSecretKeys:
    - iam_username
    - iam_password
  versions:
  - name: v1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          # Resource name, type and policy arn as API input
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  resourceName:
                    description: The name that is used for IAM user creation. User the same name as resource name for resource policy lookup to work.
                    type: string
                  resourceType:
                    description: A string used as a part of prefix in IAM creation. 
                    type: string
                  policyARN:
                    description: ARN of the resource policy. User as a attachement to the user.
                    type: string
                  secretNamespace:
                    description: namespace to store the secret 
                    type: string
                required:
                  - resourceName
                  - resourceType
                  - policyARN
                  - secretNamespace
            required:
              - parameters