apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xwebapplications.learn.unified.devops
spec:
  group: learn.unified.devops
  names:
    kind: XWebApplication
    plural: xwebapplications
  claimNames:
    kind: WebApplication
    plural: webapplications
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  productGitGroup:
                    type: string
                  databaseSize:
                    type: string
                required:
                - productGitGroup
                - databaseSize
            required:
            - parameters