apiVersion: xrd-breaking.imarunrk.com/v1
kind: MySql
metadata:
  namespace: alpha
  name: my-db
  labels:
    claim.name: my-db
spec:
  compositionRef:
    name: gcp-mysql
  parameters:
    size: 10
    vm: db-n1-standard-2