apiVersion: gcp.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: product-a
spec:
  projectID: crossplane-339717
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: gcp-account
      key: service-account