---
apiVersion: pkg.crossplane.io/v1alpha1
kind: ControllerConfig
metadata:
  name: allow-prometheus
spec:
  metadata:
    labels:
      crossplane.io/provider: "true"
  ports:
  - name: metrics 
    containerPort: 8080
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-gcp
spec:
  package: crossplane/provider-gcp:v0.18.0
  controllerConfigRef:
    name: allow-prometheus