apiVersion: database.gcp.crossplane.io/v1beta1
kind: CloudSQLInstance
metadata:
  name: db-gcp-new
spec:
  providerConfigRef:
    name: gcp-credentials-project-1
  writeConnectionSecretToRef:
    namespace: crossplane-system
    name: db-ssdss
  forProvider:
    databaseVersion: POSTGRES_9_621
    region: us-central
    settings:
      tier: db-g1-small
      dataDiskSizeGb: 20