apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: gitprojects-composition
spec:
  compositeTypeRef:
    apiVersion: learn.unified.devops/v1alpha1
    kind: XGitProject
  resources:
  - name: gitlab-project
    base:
      apiVersion: projects.gitlab.crossplane.io/v1alpha1
      kind: Project
      spec:
        providerConfigRef:
          name: # Patch
        forProvider:
          visibility: public
          publicBuilds: true
    patches:
    - fromFieldPath: spec.claimRef.name
      toFieldPath: metadata.name
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.providerConfigRef.name
    - fromFieldPath: spec.claimRef.namespace
      toFieldPath: spec.writeConnectionSecretToRef.namespace
    - fromFieldPath: spec.claimRef.name
      toFieldPath: spec.writeConnectionSecretToRef.name
      transforms:
        - type: string
          string:
            fmt: "%s-repo-key"
    - fromFieldPath: spec.parameters.gitlabGroupID
      toFieldPath: spec.forProvider.namespaceId  
    - fromFieldPath: spec.claimRef.name
      toFieldPath: spec.forProvider.description
      transforms:
        - type: string
          string:
            fmt: "The %s react project"
    - type: FromCompositeFieldPath
      fromFieldPath: spec.parameters.template
      toFieldPath: spec.forProvider.importUrl
      transforms:
      - type: map
        map:
          react-web: https://gitlab.com/unified.devops/react-template.git
          node-backend: https://gitlab.com/unified.devops/react-template.git
          spring-boot-web: https://gitlab.com/unified.devops/react-template.git
          spring-boot-api: https://gitlab.com/unified.devops/react-template.git
    - type: ToCompositeFieldPath
      fromFieldPath: status.atProvider.httpUrlToRepo
      toFieldPath: status.projectRepo
    connectionDetails:
    - name: gitlabToken
      fromConnectionSecretKey: runnersToken
    - name: gitlabProjectURL
      fromFieldPath: status.atProvider.httpUrlToRepo